---
- hosts: all
  vars_files:
    - "group_vars/os_{{ ansible_distribution }}.yml"
    - "group_vars/env_{{ env }}.yml"
    - "host_vars/{{ ansible_hostname }}.yml"
  roles:
    - common
    - doas
    - openntpd
    - aliases
#    - pf

- include: dnsservers.yml
- include: vpnservers.yml
