---
- name: disable pi user
  ansible.builtin.user:
    name: "pi"
    password: "*"
    state: present

- name: remove ssh public keys for pi user
  ansible.builtin.file:
    path: "/home/pi/.ssh"
    state: absent

- name: remove sudo for pi users
  community.general.sudoers:
    name: "010_pi-nopasswd"
    user: "pi"
    state: absent

- name: enable cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot
  when: enable_cgroup
