---
- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) }}"
    state: present
    shell: /bin/bash
  with_items: "{{ users }}"

- name: Install ssh public keys for new users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.pubkey }}"
    state: present
  with_items: "{{ users }}"

- name: Enable sudo for new users
  community.general.sudoers:
    name: "010_{{ item.name }}-nopasswd"
    user: "{{ item.name }}"
    nopassword: true
    commands: "ALL"
  when: "item.sudo | default(false)"
  with_items: "{{ users }}"
