- name: reload k3s
  ansible.builtin.service:
    name: k3s
    state: reloaded

- name: restart k3s
  ansible.builtin.service:
    name: k3s
    state: restarted

- name: reload systemd
  command: "systemctl daemon-reload"
